# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jesús Redondo Garcia
email: redondogarciajesus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Webpage of Jesús Redondo García. This will serve as blog, showcase and personal story telling board.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jesusredondo.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: musicaligera_
github_username:  jesusredondo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-87745144-1

disqus:
  shortname: https-jesusredondo-github-io


##APPLY TO ALL 
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true

